### ISSUE TITLE
Child variants

### ISSUE THREAD

**Issue by srph** [rstacruz/rscss#10]
I'm into utility classes. How do I write the _clearfix hack_ with this guide? Given that this implementation usually consists of **3** classes, `clearfix`, `left`, and `right` (`left` and `right` being the _Child invariants_ (not sure what to call them)).

I find the example below okay.

``` stylus
.u-clearfix
  //

  .-left
    float: left;

  .-right
    float: right;
```

But I thought maybe we could use double hyphens (`--`) to indicate child variants, like the refactor below:

``` stylus
.u-clearfix
  //

  .--left
    float: left;

  .--right
    float: right;
```

**Comment by rstacruz** [comment]
rscss doesn't have any provisions for utility classes.

this is beyond the scope of rscss. you might see `.clearfix` + `.pull-left` + `.pull-right` in Bootstrap, but IMHO that's because bootstrap is made with rapid prototyping framework cases in mind, while rscss (and bem/smacss/et al) were devised to be guidelines for building full UIs from scratch.

imho, though, it's probably best to just use a mixin for that. you may also want to consider that your floating rules will probably change as you make your site responsive, so i'd encourage thinking twice about making them as utility classes.
